// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiceMNxC1oAMQRLQZUuLIKxM3TkGuff5U',
    appId: '1:965431400148:web:4a620255a7e23e87000d41',
    messagingSenderId: '965431400148',
    projectId: 'flutter-bookstore-2c9aa',
    authDomain: 'flutter-bookstore-2c9aa.firebaseapp.com',
    databaseURL: 'https://flutter-bookstore-2c9aa-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-bookstore-2c9aa.firebasestorage.app',
    measurementId: 'G-L07DF5PRJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF_UgmfTavJVT7e5UwdVnlkFmt1TJMPDk',
    appId: '1:965431400148:android:498db8bd1ded7789000d41',
    messagingSenderId: '965431400148',
    projectId: 'flutter-bookstore-2c9aa',
    databaseURL: 'https://flutter-bookstore-2c9aa-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-bookstore-2c9aa.firebasestorage.app',
  );
}
